### PR TITLE
Installer

### PR DESCRIPTION
**Pull request by harikt**
Hi, 

I have updated with docs. If you like, you can merge.

Thanks

### CODE REVIEW

**Comment by marcus-herrmann** [comment]
Thanks for this - will test-drive this asap, and really looking forward to it!

**Comment by marcus-herrmann** [comment]
Hi Hari KT,

again, thanks for this contribution! While trying it out I learned that the best way of using it in MAMP is `$ wireshell one-click-install baz --dbHost=127.0.0.1 --chmodDir=777`.

Two more things:
- I'd propose to name this command "New", replacing the old "New" command (which was basically just a download command anyway) - but somehow it's a dependency for your command? See below
- In this sense, could you add an option like `--no-install` to your command that make the installer exit just after downloading (mimicking old "New" commands functionality)?
- Shortly I'll restructure the `src` folder, putting command files into their own folder and namespace, as well as other dependencies. Could you open a new PR shortly after this change hits master (or, dev) branch?
- I'm not sure about some unused methods in your class e.g. `download()` and `checkProcesswireRequirements()`. Also it is not clear that NewCommand is a depencency of your installer. Is there a possibility to refactor that?
- Could you modify the leading comment (line 2-11) and the overall spelling of ProcessWire?
- Often times I'm not sure if I understand the DocBlock `@return NewCommand` - how is an instance of this class returned by this method?

**Comment by harikt** [comment]
Hi @marcus-herrmann , 

Thanks for your feedback.

If possible some of your comments may be good to be on the code block.

Eg: things like 

> Could you modify the leading comment (line 2-11) 

If the line you are talking is about copyright to Fabien. I would like it to stay like that for I have modified the same from the Symfony installer.

> and the overall spelling of ProcessWire?

Not sure about the spelling issue :( . May be you can explain a bit ?

> Often times I'm not sure if I understand the DocBlock @return NewCommand - how is an instance of this class returned by this method?

Funny that I have ported this from a command that I created named `NewCommand` ;) . So we have created the installer for sometime.

**Comment by marcus-herrmann** [comment]
Sure about the copyright, but for consistency please add something like this on top:

```
/**
 * Class FooBarBaz
 *
 * Installs ProcessWire
 *
 * @package Wireshell
 * @author {Your Name}
 */
```

Regarding spelling: Only a detail, but sometimes it's Processwire, then processwire, then ProcessWire, in both function names and comments. You're right - am going to use code comments in the file itself from now on :+1:

**Comment by harikt** [comment]
@marcus-herrmann sure. I will work on with your comments.

Please give me a few days.

**Comment by marcus-herrmann** [comment]
Sure! 

Here's said `development` branch with the aforementioned folder structure: https://github.com/marcus-herrmann/wireshell/tree/develop

**Comment by harikt** [comment]
Closing.

Will open to develop branch.

**Pull request closed without merging**
