### PR TITLE
start implementing DiagnoseModules from @netcarver

### PR DESCRIPTION
**Pull request by horst-n**
Implemented the ProcessDiagnostics as parent, that all submodules have to extend.
Added the submodules PHP and Imagehandling in a rudimentary way, only using title and value, statuses like ok | warning and additional infos are currently omitted.

### CODE REVIEW

**Comment by horst-n** [comment]
@marcus-herrmann: please have a look to it and modify where you see fit. If you have setup it how you like it, I can add some more of the sub modules, or maybe @nico sheems in and adds one too. :)

**Comment by marcus-herrmann** [comment]
:+1:

**Comment by nico** [comment]
wrong nico?

**Comment by marcus-herrmann** [comment]
Yeah, @horst-n was referring to @NicoKnoll

**Pull request merged**
